const AUTO_GENERATED_PLAYFUN_DISPLAY_NAME_PATTERN = /^playfun-(?:[a-z0-9]{16}|player)$/;

export function isAutoGeneratedPlayfunDisplayName(displayName: string | null | undefined): boolean {
  return typeof displayName === 'string' && AUTO_GENERATED_PLAYFUN_DISPLAY_NAME_PATTERN.test(displayName);
}
