const PLAYFUN_DISPLAY_NAME_PREFIX = 'playfun-';
const AUTO_GENERATED_PLAYFUN_DISPLAY_NAME_PATTERN = /^playfun-(?:[a-z0-9]{16}|player)$/i;

export function hasPlayfunDisplayNamePrefix(
  displayName: string | null | undefined
): boolean {
  return typeof displayName === 'string'
    && displayName.trim().toLowerCase().startsWith(PLAYFUN_DISPLAY_NAME_PREFIX);
}

export function isAutoGeneratedPlayfunDisplayName(displayName: string | null | undefined): boolean {
  return typeof displayName === 'string'
    && AUTO_GENERATED_PLAYFUN_DISPLAY_NAME_PATTERN.test(displayName.trim());
}

export function isPlayfunLeaderboardExcludedDisplayName(
  displayName: string | null | undefined
): boolean {
  return hasPlayfunDisplayNamePrefix(displayName);
}
