/* eslint-disable */
// Generated by Wrangler by running `wrangler types generated-bindings/api-worker-configuration.d.ts --env-interface ApiBindings --include-runtime false --strict-vars false` (hash: a562f203a79e14aae524a2af6faeb4c8)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/cloudflare/worker");
	}
	interface SafetyEnv {
		WORLD_TILE_BUCKET: R2Bucket;
		DB: D1Database;
		JAM_DB: D1Database;
		WORLD_TILE_QUEUE: Queue;
		ENABLE_TEST_RESET: string;
		JAM_SUBMISSIONS_OPEN_AT: string;
		JAM_SUBMISSIONS_CLOSE_AT: string;
		PARTYKIT_HOST: string;
		PARTYKIT_PARTY: string;
		ROOM_MINT_DISABLED: string;
		ROOM_DAILY_CLAIM_LIMIT: string;
		PLAYABLE_CONTENT_INDEX_READS: string;
		COMPACT_WORLD_READS: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		TILED_OVERWORLD_READS: string;
		TILED_OVERWORLD_ROLLOUT_PERCENT: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
	}
	interface Env {
		WORLD_TILE_BUCKET: R2Bucket;
		DB: D1Database;
		JAM_DB: D1Database;
		WORLD_TILE_QUEUE: Queue;
		ENABLE_TEST_RESET?: string;
		JAM_SUBMISSIONS_OPEN_AT: string;
		JAM_SUBMISSIONS_CLOSE_AT: string;
		PARTYKIT_HOST: string;
		PARTYKIT_PARTY: string;
		ROOM_MINT_DISABLED?: string;
		ROOM_DAILY_CLAIM_LIMIT: string;
		PLAYABLE_CONTENT_INDEX_READS: string;
		COMPACT_WORLD_READS: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		TILED_OVERWORLD_READS: string;
		TILED_OVERWORLD_ROLLOUT_PERCENT: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
		ASSETS?: Fetcher;
	}
}
interface ApiBindings extends Cloudflare.Env {}
