/* eslint-disable */
// Generated by Wrangler by running `wrangler types generated-bindings/api-worker-configuration.d.ts --env-interface ApiBindings --include-runtime false --strict-vars false` (hash: 40e0352f23d648e2f4f7f79b0e91cd60)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/cloudflare/worker");
	}
	interface SafetyEnv {
		RUN_GHOST_BUCKET: R2Bucket;
		WORLD_TILE_BUCKET: R2Bucket;
		DB: D1Database;
		JAM_DB: D1Database;
		WORLD_TILE_QUEUE: Queue;
		ENABLE_TEST_RESET: string;
		RUN_GHOST_COST_ALERTS_ENABLED: string;
		RUN_GHOST_BILLING_CYCLE_DAY: string;
		ENABLE_SNAPSHOT_ADMIN: string;
		JAM_SUBMISSIONS_OPEN_AT: string;
		JAM_SUBMISSIONS_CLOSE_AT: string;
		PARTYKIT_HOST: string;
		PARTYKIT_PARTY: string;
		ROOM_MINT_DISABLED: string;
		ROOM_DAILY_CLAIM_LIMIT: string;
		PLAYABLE_CONTENT_INDEX_READS: string;
		COMPACT_WORLD_READS: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		WORLDS_ENABLED: string;
		TILED_OVERWORLD_READS: string;
		TILED_OVERWORLD_ROLLOUT_PERCENT: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
	}
	interface Env {
		RUN_GHOST_BUCKET: R2Bucket;
		WORLD_TILE_BUCKET: R2Bucket;
		DB: D1Database;
		JAM_DB: D1Database;
		WORLD_TILE_QUEUE: Queue;
		ENABLE_TEST_RESET?: string;
		RUN_GHOST_COST_ALERTS_ENABLED: string;
		RUN_GHOST_BILLING_CYCLE_DAY: string;
		ENABLE_SNAPSHOT_ADMIN?: string;
		JAM_SUBMISSIONS_OPEN_AT: string;
		JAM_SUBMISSIONS_CLOSE_AT: string;
		PARTYKIT_HOST: string;
		PARTYKIT_PARTY: string;
		ROOM_MINT_DISABLED?: string;
		ROOM_DAILY_CLAIM_LIMIT: string;
		PLAYABLE_CONTENT_INDEX_READS: string;
		COMPACT_WORLD_READS: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		WORLDS_ENABLED: string;
		TILED_OVERWORLD_READS: string;
		TILED_OVERWORLD_ROLLOUT_PERCENT: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
		ASSETS?: Fetcher;
		WORLD_MAP_HEALTH_ALERTS_ENABLED?: string;
	}
}
interface ApiBindings extends Cloudflare.Env {}
