/* eslint-disable */
// Generated by Wrangler by running `wrangler types generated-bindings/world-tile-renderer-worker-configuration.d.ts --config wrangler.world-tile-renderer.jsonc --env-interface WorldTileRendererBindings --include-runtime false --strict-vars false` (hash: b47df67416a49f4acf0f147bbc784af4)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/cloudflare/world-tile-renderer-worker");
	}
	interface SafetyEnv {
		WORLD_TILES: R2Bucket;
		DB: D1Database;
		WORLD_TILE_RENDER_QUEUE: Queue;
		WORLD_TILE_BROWSER: Fetcher;
		WORLD_TILE_ENVIRONMENT: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		WORLD_TILE_LEASE_SECONDS: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
	}
	interface Env {
		WORLD_TILES: R2Bucket;
		DB: D1Database;
		WORLD_TILE_RENDER_QUEUE: Queue;
		WORLD_TILE_BROWSER: Fetcher;
		WORLD_TILE_ENVIRONMENT: string;
		WORLD_TILE_GENERATION_ENABLED: string;
		WORLD_TILE_LEASE_SECONDS: string;
		WORLD_TILE_PUBLIC_BASE_URL: string;
	}
}
interface WorldTileRendererBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORLD_TILE_ENVIRONMENT" | "WORLD_TILE_GENERATION_ENABLED" | "WORLD_TILE_LEASE_SECONDS" | "WORLD_TILE_PUBLIC_BASE_URL">> {}
}
