import { hasPlayfunDisplayNamePrefix } from '../../../playfun/identity';
import { requireAdminRequest } from '../auth/request';
import { jsonResponse, parseJsonBody } from '../core/http';
import type { Env, PointEventRow } from '../core/types';
import { upsertUserStats } from '../runs/points';
import {
  sqlHasPlayfunDisplayNamePrefix,
  sqlUserIdIsPlayfunOnly,
} from '../playfun/leaderboardIsolation';

interface CleanupRequestBody {
  apply?: boolean;
}

interface PlayfunDisplayNameUserRow {
  user_id: string;
}

interface PlayfunRunRow {
  attempt_id: string;
  user_id: string;
}

interface AutoGeneratedPlayfunUserRow {
  id: string;
  display_name: string;
}

export interface PlayfunLeaderboardCleanupSummary {
  apply: boolean;
  burnerUserCount: number;
  roomRunCount: number;
  courseRunCount: number;
  burnerPointEventCount: number;
  creatorPointEventCount: number;
  burnerUserStatsCount: number;
  affectedUserCount: number;
  burnerUserIds: string[];
  affectedUserIds: string[];
  roomRunAttemptIds: string[];
  courseRunAttemptIds: string[];
  creatorPointEventIds: string[];
  playfunDisplayNamesWithoutLink: Array<{
    userId: string;
    displayName: string;
  }>;
}

export async function handleAdminPlayfunLeaderboardCleanup(
  request: Request,
  env: Env
): Promise<Response> {
  requireAdminRequest(env, request, 'clean up Play.fun leaderboard data');
  const body = await parseJsonBody<CleanupRequestBody>(request);
  const apply = body?.apply === true;

  const summary = apply
    ? await applyPlayfunLeaderboardCleanup(env)
    : await previewPlayfunLeaderboardCleanup(env);
  return jsonResponse(request, summary, {
    headers: {
      'Cache-Control': 'no-store',
    },
  });
}

export async function previewPlayfunLeaderboardCleanup(
  env: Env
): Promise<PlayfunLeaderboardCleanupSummary> {
  const burnerUsers = await env.DB.prepare(
    `
      SELECT id AS user_id
      FROM users
      WHERE ${sqlUserIdIsPlayfunOnly('id')}
      ORDER BY id ASC
    `
  ).all<PlayfunDisplayNameUserRow>();
  const roomRuns = await env.DB.prepare(
    `
      SELECT attempt_id, user_id
      FROM room_runs
      WHERE ${sqlUserIdIsPlayfunOnly('room_runs.user_id')}
      ORDER BY attempt_id ASC
    `
  ).all<PlayfunRunRow>();
  const courseRuns = await env.DB.prepare(
    `
      SELECT attempt_id, user_id
      FROM course_runs
      WHERE ${sqlUserIdIsPlayfunOnly('course_runs.user_id')}
      ORDER BY attempt_id ASC
    `
  ).all<PlayfunRunRow>();
  const creatorPointEvents = await env.DB.prepare(
    `
      SELECT id, user_id, event_type, source_key, points, breakdown_json, created_at
      FROM point_events
      WHERE event_type IN ('room_creator_completion', 'course_creator_completion')
        AND breakdown_json IS NOT NULL
        AND ${sqlUserIdIsPlayfunOnly(`json_extract(breakdown_json, '$.finisherUserId')`)}
      ORDER BY created_at ASC, id ASC
    `
  ).all<PointEventRow>();
  const burnerPointEventCountRow = await env.DB.prepare(
    `
      SELECT COUNT(*) AS count
      FROM point_events
      WHERE ${sqlUserIdIsPlayfunOnly('point_events.user_id')}
    `
  ).first<{ count: number | string | null }>();
  const burnerUserStatsCountRow = await env.DB.prepare(
    `
      SELECT COUNT(*) AS count
      FROM user_stats
      WHERE ${sqlUserIdIsPlayfunOnly('user_stats.user_id')}
    `
  ).first<{ count: number | string | null }>();
  const maybeAutoGeneratedUsers = await env.DB.prepare(
    `
      SELECT id, display_name
      FROM users
      WHERE ${sqlHasPlayfunDisplayNamePrefix('display_name')}
        AND NOT EXISTS (
          SELECT 1
          FROM playfun_user_links playfun_user_links
          WHERE playfun_user_links.user_id = users.id
        )
      ORDER BY display_name ASC
    `
  ).all<AutoGeneratedPlayfunUserRow>();

  const burnerUserIds = burnerUsers.results.map((row) => row.user_id);
  const affectedUserIds = new Set<string>(burnerUserIds);
  for (const pointEvent of creatorPointEvents.results) {
    affectedUserIds.add(pointEvent.user_id);
  }

  return {
    apply: false,
    burnerUserCount: burnerUserIds.length,
    roomRunCount: roomRuns.results.length,
    courseRunCount: courseRuns.results.length,
    burnerPointEventCount: Math.max(0, Number(burnerPointEventCountRow?.count ?? 0)),
    creatorPointEventCount: creatorPointEvents.results.length,
    burnerUserStatsCount: Math.max(0, Number(burnerUserStatsCountRow?.count ?? 0)),
    affectedUserCount: affectedUserIds.size,
    burnerUserIds,
    affectedUserIds: [...affectedUserIds].sort(),
    roomRunAttemptIds: roomRuns.results.map((row) => row.attempt_id),
    courseRunAttemptIds: courseRuns.results.map((row) => row.attempt_id),
    creatorPointEventIds: creatorPointEvents.results.map((row) => row.id),
    playfunDisplayNamesWithoutLink: maybeAutoGeneratedUsers.results
      .filter((row) => hasPlayfunDisplayNamePrefix(row.display_name))
      .map((row) => ({
        userId: row.id,
        displayName: row.display_name,
      })),
  };
}

export async function applyPlayfunLeaderboardCleanup(
  env: Env
): Promise<PlayfunLeaderboardCleanupSummary> {
  const preview = await previewPlayfunLeaderboardCleanup(env);

  await env.DB.batch([
    env.DB.prepare(
      `
        DELETE FROM room_runs
        WHERE ${sqlUserIdIsPlayfunOnly('room_runs.user_id')}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM course_runs
        WHERE ${sqlUserIdIsPlayfunOnly('course_runs.user_id')}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM point_events
        WHERE ${sqlUserIdIsPlayfunOnly('point_events.user_id')}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM point_events
        WHERE event_type IN ('room_creator_completion', 'course_creator_completion')
          AND breakdown_json IS NOT NULL
          AND ${sqlUserIdIsPlayfunOnly(`json_extract(breakdown_json, '$.finisherUserId')`)}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM user_stats
        WHERE ${sqlUserIdIsPlayfunOnly('user_stats.user_id')}
      `
    ),
  ]);

  for (const userId of preview.affectedUserIds) {
    await upsertUserStats(env, userId);
  }

  return {
    ...preview,
    apply: true,
  };
}
