import { isAutoGeneratedPlayfunDisplayName } from '../../../playfun/identity';
import { requireAdminRequest } from '../auth/request';
import { jsonResponse, parseJsonBody } from '../core/http';
import type { Env, PointEventRow } from '../core/types';
import { upsertUserStats } from '../runs/points';
import { sqlIsPlayfunLinkedUser } from '../playfun/leaderboardIsolation';

interface CleanupRequestBody {
  apply?: boolean;
}

interface PlayfunLinkedUserRow {
  user_id: string;
}

interface PlayfunRunRow {
  attempt_id: string;
  user_id: string;
}

interface AutoGeneratedPlayfunUserRow {
  id: string;
  display_name: string;
}

export interface PlayfunLeaderboardCleanupSummary {
  apply: boolean;
  linkedUserCount: number;
  roomRunCount: number;
  courseRunCount: number;
  creatorPointEventCount: number;
  affectedUserCount: number;
  linkedUserIds: string[];
  affectedUserIds: string[];
  roomRunAttemptIds: string[];
  courseRunAttemptIds: string[];
  creatorPointEventIds: string[];
  autoGeneratedDisplayNamesWithoutLink: Array<{
    userId: string;
    displayName: string;
  }>;
}

export async function handleAdminPlayfunLeaderboardCleanup(
  request: Request,
  env: Env
): Promise<Response> {
  requireAdminRequest(env, request, 'clean up Play.fun leaderboard data');
  const body = await parseJsonBody<CleanupRequestBody>(request);
  const apply = body?.apply === true;

  const summary = apply
    ? await applyPlayfunLeaderboardCleanup(env)
    : await previewPlayfunLeaderboardCleanup(env);
  return jsonResponse(request, summary, {
    headers: {
      'Cache-Control': 'no-store',
    },
  });
}

export async function previewPlayfunLeaderboardCleanup(
  env: Env
): Promise<PlayfunLeaderboardCleanupSummary> {
  const linkedUsers = await env.DB.prepare(
    `
      SELECT user_id
      FROM playfun_user_links
      ORDER BY user_id ASC
    `
  ).all<PlayfunLinkedUserRow>();
  const roomRuns = await env.DB.prepare(
    `
      SELECT attempt_id, user_id
      FROM room_runs
      WHERE ${sqlIsPlayfunLinkedUser('room_runs.user_id')}
      ORDER BY attempt_id ASC
    `
  ).all<PlayfunRunRow>();
  const courseRuns = await env.DB.prepare(
    `
      SELECT attempt_id, user_id
      FROM course_runs
      WHERE ${sqlIsPlayfunLinkedUser('course_runs.user_id')}
      ORDER BY attempt_id ASC
    `
  ).all<PlayfunRunRow>();
  const creatorPointEvents = await env.DB.prepare(
    `
      SELECT id, user_id, event_type, source_key, points, breakdown_json, created_at
      FROM point_events
      WHERE event_type IN ('room_creator_completion', 'course_creator_completion')
        AND breakdown_json IS NOT NULL
        AND ${sqlIsPlayfunLinkedUser(`json_extract(breakdown_json, '$.finisherUserId')`)}
      ORDER BY created_at ASC, id ASC
    `
  ).all<PointEventRow>();
  const maybeAutoGeneratedUsers = await env.DB.prepare(
    `
      SELECT id, display_name
      FROM users
      WHERE display_name LIKE 'playfun-%'
        AND NOT EXISTS (
          SELECT 1
          FROM playfun_user_links playfun_user_links
          WHERE playfun_user_links.user_id = users.id
        )
      ORDER BY display_name ASC
    `
  ).all<AutoGeneratedPlayfunUserRow>();

  const linkedUserIds = linkedUsers.results.map((row) => row.user_id);
  const affectedUserIds = new Set<string>(linkedUserIds);
  for (const pointEvent of creatorPointEvents.results) {
    affectedUserIds.add(pointEvent.user_id);
  }

  return {
    apply: false,
    linkedUserCount: linkedUserIds.length,
    roomRunCount: roomRuns.results.length,
    courseRunCount: courseRuns.results.length,
    creatorPointEventCount: creatorPointEvents.results.length,
    affectedUserCount: affectedUserIds.size,
    linkedUserIds,
    affectedUserIds: [...affectedUserIds].sort(),
    roomRunAttemptIds: roomRuns.results.map((row) => row.attempt_id),
    courseRunAttemptIds: courseRuns.results.map((row) => row.attempt_id),
    creatorPointEventIds: creatorPointEvents.results.map((row) => row.id),
    autoGeneratedDisplayNamesWithoutLink: maybeAutoGeneratedUsers.results
      .filter((row) => isAutoGeneratedPlayfunDisplayName(row.display_name))
      .map((row) => ({
        userId: row.id,
        displayName: row.display_name,
      })),
  };
}

export async function applyPlayfunLeaderboardCleanup(
  env: Env
): Promise<PlayfunLeaderboardCleanupSummary> {
  const preview = await previewPlayfunLeaderboardCleanup(env);

  await env.DB.batch([
    env.DB.prepare(
      `
        DELETE FROM room_runs
        WHERE ${sqlIsPlayfunLinkedUser('room_runs.user_id')}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM course_runs
        WHERE ${sqlIsPlayfunLinkedUser('course_runs.user_id')}
      `
    ),
    env.DB.prepare(
      `
        DELETE FROM point_events
        WHERE event_type IN ('room_creator_completion', 'course_creator_completion')
          AND breakdown_json IS NOT NULL
          AND ${sqlIsPlayfunLinkedUser(`json_extract(breakdown_json, '$.finisherUserId')`)}
      `
    ),
  ]);

  for (const userId of preview.affectedUserIds) {
    await upsertUserStats(env, userId);
  }

  return {
    ...preview,
    apply: true,
  };
}
